[feature/member] close #14
cau-rubato/rubato-backend pull request #59
Opened 2022-07-20 07:05 UTC by AllyHyeseongKim

1. Create the controller, service, repository of ClubMember, Manager domain
2. Create the unit test

2022-07-20 07:57 UTC, bkRyusim requested changes
4 requests required to change

2022-07-20 07:57 UTC, bkRyusim commented on src/main/java/org/rubatophil/www/api/controller/ClubMemberController.java
> +                .profileImage(newClubMember.getProfileImage() == null ? null : newClubMember.getProfileImage())
```suggestion
                .profileImage(newClubMember.getProfileImage())
```

2022-07-20 07:57 UTC, bkRyusim commented on src/main/java/org/rubatophil/www/api/repository/DepartmentRepository.java
> +import java.util.Optional;
```suggestion
```

2022-07-20 07:57 UTC, bkRyusim commented on src/main/java/org/rubatophil/www/api/controller/ManagerController.java
> +        List<ManagerResponse> managerList = new ArrayList<>();
Response를 Manager들의 List 형식으로 주지 말고 'president', 'vicePresident', 'secretary' 각각의 key를 가진 Response로 형식을 바꾸어 주세요

2022-07-20 07:57 UTC, bkRyusim commented on src/test/java/org/rubatophil/www/api/controller/ManagerControllerTest.java
> +        String expectedJson = "[{\"managerType\":\"PRESIDENT\",\"name\":\"president\",\"profileImage\":null,\"instrument\":[\"VIOLIN\"],\"generation\":34,\"department\":\"test college\",\"admissionYe
Controller의 수정 사항에 따라 response 형식을 바꾸어 주세요

2022-07-21 10:56 UTC, AllyHyeseongKim reviewed
LGTM

2022-07-21 16:29 UTC, bkRyusim commented on src/main/java/org/rubatophil/www/api/response/ManagerResponse.java
> +    public ManagerResponse(Manager manager) {
Builder가 아니라 `fromEntity()` 같은 이름의 다른 메소드면 좋을 것 같아요

2022-07-21 16:35 UTC, bkRyusim commented on src/test/java/org/rubatophil/www/api/controller/ManagerControllerTest.java
> +        this.managers.add(this.secretary);
```suggestion
```

2022-07-21 16:44 UTC, bkRyusim requested changes
8 small changes required

2022-07-21 16:44 UTC, bkRyusim commented on src/test/java/org/rubatophil/www/api/controller/ManagerControllerTest.java
> +        this.managers.add(null);
```suggestion
```

2022-07-21 16:44 UTC, bkRyusim commented on src/test/java/org/rubatophil/www/api/service/ManagerServiceTest.java
> +
```suggestion
```

2022-07-21 16:53 UTC, bkRyusim approved these changes
LGTM

2022-07-21 16:54 UTC, merged